### ISSUE TITLE
the preview image is broken as a gray

### ISSUE THREAD

**Issue by dudgus0627** [jiangdongguo/AndroidUSBCamera#307]
When returning after switching to another app, the preview image is broken as a gray.
I tried to get camera images on "onFrame" IFrameCallback (AbstractUVCCameraHandler.java), I've also got the same broken images.
Maybe it occurred on NativeCode.
Could you check this issue?

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try

**Comment by am3n** [comment]
In version 3.1.8, sometimes the frame rate reaches the minimum possible and the image becomes completely gray

**Comment by jiangdongguo** [comment]
how about 3.3.3？

**Comment by jiangdongguo** [comment]
update to new of master and have a try

**Comment by am3n** [comment]
I have updated to the latest commit, the situation is better than before and the problem occurs less, thanks for that.
But because the problem is not completely solved, it is not possible to use it in production mode.
I don't know exactly where the problem is, I was trying to replace MediaCodec with Surface and GLES and convert H264 directly to YUV and then to Bitmap, but it didn't work. It seems that the UVC library does not work without Surface Preview.

**Comment by jiangdongguo** [comment]
Can you show me the record video?

**Comment by am3n** [comment]
https://drive.google.com/file/d/1cBUKC9Nm4yEtA0UpWfSNuHVZRsjvpPRG/view?usp=sharing

**Comment by BruceZhang2017** [comment]
@jiangdongguo 这个问题还是存在的3.3.3。
